services:
  # MCP Server
  mcp-server:
    build: .
    container_name: django-vue-mcp-server
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./docs:/app/docs
      - ./tests:/app/tests
      - ./.env:/app/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - DOCKER_MODE=true
      - HTTP_MODE=true  # Enable OAuth web mode
      - HEALTH_PORT=8080
      - WEB_PORT=8000
      - BASE_URL=http://localhost:8000
      - GITHUB_CLIENT_ID=Ov23libL0xJY8V37jSxf
      - GITHUB_CLIENT_SECRET=4a61b1a96b03cd6aea9f3a10c7e8716cdae6bd44
      - JWT_SECRET=docker_jwt_secret_minimum_32_characters_long_for_security
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - mcp-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: django-vue-mcp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - mcp-network

  # Development Tools Container (optional)
  dev-tools:
    build: .
    container_name: django-vue-mcp-dev
    volumes:
      - ./:/app
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    depends_on:
      - redis
    networks:
      - mcp-network
    profiles:
      - dev

volumes:
  redis_data:

networks:
  mcp-network:
    driver: bridge